#!/usr/bin/env tsx
/**
 * Build the verified-financials snapshot.
 *
 * Source priority per field (highest wins):
 *   1. XBRL (xbrl)                          — from NSE/BSE filings
 *   2. Annual report parser (annual_report) — from cited PDF
 *   3. Manual override (manual_verified)    — only with sourceDocument + page
 *
 * No estimation, no sector-ratio inference, no Screener fallback.
 * Writes to:
 *   - data/generated/verified-financials.json   (human-readable diff)
 *   - data/generated/verified-financials.ts     (typed import)
 *   - app/api/scores/snapshot.ts                (the file the Worker bundles)
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { COMPANY_SOURCE_MAP } from "../../data/company-source-map";
import { fetchAnnualReportsForCompany } from "./annual-report-parser";
import { fetchXbrlForCompany } from "./xbrl-parser";
import { loadManualOverrides } from "./manual-overrides";
import type {
  CompanyFinancialSnapshot,
  FinancialYearData,
  GeneratedFinancialSnapshot,
} from "../../lib/types";

const OUT_DIR = resolve(__dirname, "..", "..", "data", "generated");
const OUT_JSON = resolve(OUT_DIR, "verified-financials.json");
const OUT_TS = resolve(OUT_DIR, "verified-financials.ts");
const ROUTE_SNAPSHOT = resolve(
  __dirname,
  "..",
  "..",
  "app",
  "api",
  "scores",
  "snapshot.ts"
);

const blankYear = (fiscalYear: string): FinancialYearData => ({
  fiscalYear,
  sales: null,
  receivables: null,
  grossProfit: null,
  currentAssets: null,
  ppe: null,
  totalAssets: null,
  depreciation: null,
  sgaExpense: null,
  totalDebt: null,
  currentLiabilities: null,
  retainedEarnings: null,
  ebit: null,
  marketValueEquity: null,
  totalLiabilities: null,
  operatingCashFlow: null,
  netIncome: null,
  fieldStatus: {},
});

async function main() {
  const overrides = loadManualOverrides();
  const companies: Record<string, CompanyFinancialSnapshot> = {};
  let totalFields = 0;

  for (const master of COMPANY_SOURCE_MAP) {
    const years: Record<string, FinancialYearData> = {};

    // 1. XBRL (highest priority)
    let xbrl: Awaited<ReturnType<typeof fetchXbrlForCompany>> = [];
    try {
      xbrl = await fetchXbrlForCompany(master);
    } catch (e) {
      console.warn(`[xbrl] ${master.ticker}:`, e instanceof Error ? e.message : e);
    }
    for (const yr of xbrl) {
      const row = years[yr.fiscalYear] ?? blankYear(yr.fiscalYear);
      for (const f of yr.fields) {
        (row as unknown as Record<string, number>)[f.field as string] = f.value;
        row.fieldStatus![f.field as string] = "xbrl";
        totalFields += 1;
      }
      years[yr.fiscalYear] = row;
    }

    // 2. Annual report (fills only fields XBRL didn't supply)
    let arResults: Awaited<ReturnType<typeof fetchAnnualReportsForCompany>> = [];
    try {
      arResults = await fetchAnnualReportsForCompany(master);
    } catch (e) {
      console.warn(`[annual_report] ${master.ticker}:`, e instanceof Error ? e.message : e);
    }
    for (const yr of arResults) {
      const row = years[yr.fiscalYear] ?? blankYear(yr.fiscalYear);
      for (const f of yr.fields) {
        const key = f.field as string;
        if (row.fieldStatus![key] === "xbrl") continue; // XBRL wins
        (row as unknown as Record<string, number>)[key] = f.value;
        row.fieldStatus![key] = "annual_report";
        totalFields += 1;
      }
      years[yr.fiscalYear] = row;
    }

    // 3. Manual overrides (fills only fields still missing)
    for (const o of overrides) {
      if (o.ticker !== master.ticker) continue;
      const row = years[o.fiscalYear] ?? blankYear(o.fiscalYear);
      const key = o.field as string;
      const existing = row.fieldStatus![key];
      if (existing && existing !== "manual_verified") continue; // higher priority wins
      (row as unknown as Record<string, number>)[key] = o.value;
      row.fieldStatus![key] = "manual_verified";
      totalFields += 1;
      years[o.fiscalYear] = row;
    }

    const yearCount = Object.keys(years).length;
    companies[master.ticker] = {
      companyName: master.companyName,
      ticker: master.ticker,
      screenerSlug: master.ticker, // legacy field, unused by verified path
      sector: master.sector,
      isFinancialCompany: master.isFinancialCompany,
      status: yearCount > 0 ? "ok" : "no_data",
      years,
    };
  }

  const snapshot: GeneratedFinancialSnapshot = {
    generatedAt: new Date().toISOString(),
    source: "official_filings_pipeline",
    companies,
  };

  mkdirSync(OUT_DIR, { recursive: true });
  const body = JSON.stringify(snapshot, null, 2);
  writeFileSync(OUT_JSON, body + "\n", "utf8");
  const ts = `// Auto-generated by scripts/ingest/build-verified-financials.ts.\nimport type { GeneratedFinancialSnapshot } from "@/lib/types";\nconst snapshot: GeneratedFinancialSnapshot = ${body};\nexport default snapshot;\n`;
  writeFileSync(OUT_TS, ts, "utf8");
  // GUARD: never overwrite the route's bundled snapshot with an empty
  // build.  We only update the runtime snapshot once parsers/overrides
  // have actually produced non-zero field values.
  if (totalFields > 0) {
    writeFileSync(ROUTE_SNAPSHOT, ts, "utf8");
    console.log(`[ingest] wrote ${ROUTE_SNAPSHOT} (totalFields=${totalFields})`);
  } else {
    console.log(
      `[ingest] SKIPPING write to ${ROUTE_SNAPSHOT}: totalFields=0 (would wipe a working snapshot). Add manual overrides or implement parsers first.`
    );
  }

  console.log(`[ingest] wrote ${OUT_JSON}`);
  console.log(`[ingest] wrote ${OUT_TS}`);
  console.log(
    `[ingest] summary: ${COMPANY_SOURCE_MAP.length} companies, ${totalFields} verified field values, manualOverrides=${overrides.length}`
  );
  if (totalFields === 0) {
    console.log(
      "[ingest] NOTE: XBRL and annual-report parsers are stubs. Add manual overrides or implement the parsers to populate fields."
    );
  }
}

main().catch((err) => {
  console.error("[ingest] fatal:", err);
  process.exit(1);
});
